services:

    php: 
      image: php:8.2-fpm
      volumes:
        - ./site:/var/www/html

    nginx:
        image: nginx:alpine
        ports:
         - "8080:80"
        volumes:
          - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
          - ./site:/var/www/html

        depends_on:
          - php