version: '3.8'

services:
  web:
    build: ./site
    ports:
      - "5000:5000"
    volumes:
      - ./site:/main

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
